main: org.hackedserver.spigot.HackedServerPlugin
name: HackedServer
version: ${projectVersion}
author: Th0rgal
softdepend: [ ViaVersion, ProtocolSupport, ProtocolLib, packetevents, Geyser-Spigot, Floodgate ]
api-version: 1.18
